apiVersion: v1
kind: Service
metadata:
  name: ci-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ci-manager.labels" . | nindent 4 }}
spec:
  type: {{.Values.service.type}}
  ports:
  - name: ci-manager
    port: {{.Values.service.port}}
    protocol: TCP
    targetPort: {{.Values.service.port}}
  - name: ci-manager-grpc
    port: {{.Values.service.grpcport}}
    protocol: TCP
    targetPort: {{.Values.service.grpcport}}     
  selector:
     {{- include "ci-manager.selectorLabels" . | nindent 4 }}