apiVersion: v1
entries:
  ci-manager:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2022-08-15T00:50:33.638416+05:30"
    dependencies:
    - name: harness-common
      repository: https://harness.github.io/helm-common/charts
      version: 0.1.1
    description: A Helm chart for Kubernetes
    digest: 76548912db50b025c714e94829a43fc76f6a5cea9fbf487505db36b37f2a4300
    name: ci-manager
    type: application
    urls:
    - ci-manager-0.1.0.tgz
    version: 0.1.0
generated: "2022-08-15T00:50:33.637177+05:30"
